<?php

/**
 * Implements hook_contextual_links_view_alter().
 *
 * Change Configure Blocks into modal links.
 */
function outside_in_contextual_links_view_alter(&$element, $items) {
  if (isset($element['#links']['outside-inblock-configure'])) {
    $element['#links']['outside-inblock-configure']['attributes'] = [
      'class' => ['use-ajax'],
      'data-dialog-type' => 'offcanvas',
    ];
  }
}
