<?php

namespace Drupal\Tests\Core\Access;

use Drupal\Core\Access\AccessGroupAnd;
use Drupal\Core\Access\AccessGroupOr;
use Drupal\Core\Access\AccessibleInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Tests\UnitTestCase;

class AccessGroupTest extends UnitTestCase {

  /**
   * @var \Drupal\Core\Session\AccountInterface
   */
  protected $account;

  protected function setUp() {
    parent::setUp(); // TODO: Change the autogenerated stub
    $this->account = $this->prophesize(AccountInterface::class)->reveal();
  }


  public function testGroups() {
    $allowedAccessible = $this->makeAccessbileProh(AccessResult::allowed());
    $forbiddenAccessible = $this->makeAccessbileProh(AccessResult::forbidden());
    $neutralAccessible = $this->makeAccessbileProh(AccessResult::neutral());



    $orForbidden = new AccessGroupOr();
    $orForbidden->addDependency($allowedAccessible)->addDependency($forbiddenAccessible);
    $this->assertTrue($orForbidden->access('view', $this->account, TRUE)->isForbidden());

    $orAllowed = new AccessGroupOr();
    $orAllowed->addDependency($allowedAccessible)->addDependency($neutralAccessible);
    $this->assertTrue($orAllowed->access('view', $this->account, TRUE)->isAllowed());

    $andNeutral = new AccessGroupAnd();
    $andNeutral->addDependency($allowedAccessible)->addDependency($neutralAccessible);
    $this->assertTrue($andNeutral->access('view', $this->account, TRUE)->isNeutral());

    // We can also add groups and dependencies!!!!! Nested!!!!!
    $andNeutral->addDependency($orAllowed);
    $this->assertTrue($andNeutral->access('view', $this->account, TRUE)->isNeutral());

    $andForbidden = $andNeutral;
    $andForbidden->addDependency($forbiddenAccessible);
    $this->assertTrue($andForbidden->access('view', $this->account, TRUE)->isForbidden());

    // We can make groups from other groups!
    $andGroupsForbidden = new AccessGroupAnd();
    $andGroupsForbidden->addDependency($andNeutral)->addDependency($andForbidden)->addDependency($orForbidden);
    $this->assertTrue($andGroupsForbidden->access('view', $this->account, TRUE)->isForbidden());
    // But then would could also add a non-group accessible.
    $andGroupsForbidden->addDependency($allowedAccessible);
    $this->assertTrue($andGroupsForbidden->access('view', $this->account, TRUE)->isForbidden());

  }

  /**
   * @param \Drupal\Core\Access\AccessResultInterface $accessResult
   *
   * @return AccessibleInterface
   */
  private function makeAccessbileProh(AccessResultInterface $accessResult) {
    $accessible = $this->prophesize(AccessibleInterface::class);
    $accessible->access('view', $this->account, TRUE)
      ->willReturn($accessResult);
    return $accessible->reveal();
  }

}
