<?php

/**
 * @file
 * Provides hook implementations for Layout Builder.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\field\FieldConfigInterface;
use Drupal\layout_builder\Entity\LayoutBuilderEntityViewDisplay;
use Drupal\layout_builder\Entity\LayoutBuilderEntityViewDisplayStorage;
use Drupal\layout_builder\Form\LayoutBuilderEntityViewDisplayForm;
use Drupal\layout_builder\EntityOperations;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_help().
 */
function layout_builder_help($route_name, RouteMatchInterface $route_match) {
  // Add help text to the Layout Builder UI.
  if ($route_match->getRouteObject()->getOption('_layout_builder')) {
    $output = '<p>' . t('This layout builder tool allows you to configure the layout of the main content area.') . '</p>';
    if (\Drupal::currentUser()->hasPermission('administer blocks')) {
      $output .= '<p>' . t('To manage other areas of the page, use the <a href="@block-ui">block administration page</a>.', ['@block-ui' => Url::fromRoute('block.admin_display')->toString()]) . '</p>';
    }
    else {
      $output .= '<p>' . t('To manage other areas of the page, use the block administration page.') . '</p>';
    }
    return $output;
  }

  switch ($route_name) {
    case 'help.page.layout_builder':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Layout Builder provides layout building utility.') . '</p>';
      $output .= '<p>' . t('For more information, see the <a href=":layout-builder-documentation">online documentation for the Layout Builder module</a>.', [':layout-builder-documentation' => 'https://www.drupal.org/docs/8/core/modules/layout_builder']) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function layout_builder_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  $entity_types['entity_view_display']
    ->setClass(LayoutBuilderEntityViewDisplay::class)
    ->setStorageClass(LayoutBuilderEntityViewDisplayStorage::class)
    ->setFormClass('edit', LayoutBuilderEntityViewDisplayForm::class);
}

/**
 * Implements hook_form_FORM_ID_alter() for \Drupal\field_ui\Form\EntityFormDisplayEditForm.
 */
function layout_builder_form_entity_form_display_edit_form_alter(&$form, FormStateInterface $form_state) {
  // Hides the Layout Builder field. It is rendered directly in
  // \Drupal\layout_builder\Entity\LayoutBuilderEntityViewDisplay::buildMultiple().
  unset($form['fields']['layout_builder__layout']);
  $key = array_search('layout_builder__layout', $form['#fields']);
  if ($key !== FALSE) {
    unset($form['#fields'][$key]);
  }
}

/**
 * Implements hook_field_config_insert().
 */
function layout_builder_field_config_insert(FieldConfigInterface $field_config) {
  // Clear the sample entity for this entity type and bundle.
  $sample_entity_generator = \Drupal::service('layout_builder.sample_entity_generator');
  $sample_entity_generator->delete($field_config->getTargetEntityTypeId(), $field_config->getTargetBundle());
  \Drupal::service('plugin.manager.block')->clearCachedDefinitions();
}

/**
 * Implements hook_field_config_delete().
 */
function layout_builder_field_config_delete(FieldConfigInterface $field_config) {
  // Clear the sample entity for this entity type and bundle.
  $sample_entity_generator = \Drupal::service('layout_builder.sample_entity_generator');
  $sample_entity_generator->delete($field_config->getTargetEntityTypeId(), $field_config->getTargetBundle());
  \Drupal::service('plugin.manager.block')->clearCachedDefinitions();
}

/**
 * Implements hook_entity_presave().
 */
function layout_builder_entity_presave(EntityInterface $entity) {
  if (\Drupal::moduleHandler()->moduleExists('block_content')) {
    /** @var \Drupal\layout_builder\EntityOperations $entity_operations */
    $entity_operations = \Drupal::classResolver(EntityOperations::class);
    $entity_operations->handlePreSave($entity);
  }
}

/**
 * Implements hook_entity_delete().
 */
function layout_builder_entity_delete(EntityInterface $entity) {
  if (\Drupal::moduleHandler()->moduleExists('block_content')) {
    /** @var \Drupal\layout_builder\EntityOperations $entity_operations */
    $entity_operations = \Drupal::classResolver(EntityOperations::class);
    $entity_operations->handleEntityDelete($entity);
  }
}

/**
 * Implements hook_cron().
 */
function layout_builder_cron() {
  if (\Drupal::moduleHandler()->moduleExists('block_content')) {
    /** @var \Drupal\layout_builder\EntityOperations $entity_operations */
    $entity_operations = \Drupal::classResolver(EntityOperations::class);
    $entity_operations->removeUnused();
  }
}

/**
 * Implements hook_plugin_filter_TYPE_alter().
 */
function layout_builder_plugin_filter_block_alter(array &$definitions, array $extra, $consumer) {
  // @todo Determine the 'inline_block_content' blocks should be allowe outside
  //   of layout_builder https://www.drupal.org/node/2979142.
  if ($consumer !== 'layout_builder') {
    foreach ($definitions as $id => $definition) {
      if ($definition['id'] === 'inline_block_content') {
        unset($definitions[$id]);
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function layout_builder_block_content_access(EntityInterface $entity, $operation, AccountInterface $account) {
  /** @var \Drupal\layout_builder\EntityOperations $entity_operations */
  $entity_operations = \Drupal::classResolver(EntityOperations::class);
  $entity_operations->handleAccessPrep($entity);
}

/**
 * Implements hook_entity_access().
 */
function xlayout_builder_entity_access(EntityInterface $entity, $operation, $account) {
  $route = \Drupal::routeMatch();
  if (strpos($route->getRouteName(), 'layout_builder.defaults') === 0 && !empty($entity->in_preview)) {
    return AccessResult::allowed();
  }
}
